server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/contabilidade;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bloquear arquivos sensíveis
    location ~ /\. {
        deny all;
    }

    error_log /var/log/nginx/contabilidade_error.log;
    access_log /var/log/nginx/contabilidade_access.log;
}
